name: Express Hostname Updater

on:
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 1 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  finding-domains:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install urllib3
          
      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 'stable'
  
      - name: SubFinder Installation
        run: |
          git clone https://github.com/projectdiscovery/subfinder.git; \
          cd subfinder/v2/cmd/subfinder; \
          go build; \
          mv subfinder /usr/local/bin/; \
          subfinder -version;

      - name: SubFinder Execution
        run: subfinder -d expressnetw.com -o express_temp.txt


      - name: Hostname Cleaup
        run: python express_hostname_cleanup.py

      - name: Configure Git
        run: |
          git config --local user.email "sudesh@sudesh.com"
          git config --local user.name "github-actions[bot]"

      - name: Commit changes
        run: |
          git add pia_servers.txt
          git diff-index --quiet HEAD || git commit -m "[AUTO] update Express VPN Hostname $(date '+%Y-%m-%d %H:%M:%S')"
          
      - name: Push changes
        id: push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}


        
        
      








  
