name: Express Hostname Updater

on:
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 1 hours
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-iocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and zmap
        run: |
          python -m pip install --upgrade pip
          pip install urllib3
          
      - name: Setup Go environment
        uses: actions/setup-go@v5.1.0
        with:
          go-version: 'stable'

      - name: Downloading subfinder
        
        run: |
          sudo go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    
          
      - name: Executing subfinder
        run: $HOME/go/bin/subfinder -d expressnetw.com -o express_temp.txt
      





  
