name: Express IP Updater

on: 
  workflow_dispatch:  # Allows manual trigger

jobs:
  update-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies and zmap
        run: |
          python -m pip install --upgrade pip
          pip install dnspython
          pip install requests
          sudo apt install zmap
          cat /etc/zmap/blacklist.conf

      - name: Gather ExpressVPN subnets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python express.py
        
      - name: Generate custom blocklist 
        run: python blocklist_generator.py


      - name: Express VPN scan
        run: sudo zmap -w express_subnet.txt -p 80 -r 128 -v 5 --output-filter="success = 1" -o 'express_ips_temp.csv' 
      
     
      - name: Clean up Express VPN output
        run: python express_vpn_cleanup.py

      - name: Express Subnet detail Generation
        run: python express_subnet_CSV.py

  
